In [5]:
from freechess.pgnparser import parse_pgn, process_pgnfile

In [6]:
import pandas as pd

In [7]:
pd.DataFrame(parse_pgn(open('freechess/fixtures/eboard.pgn').read()))

,black,blackelo,date,event,moves,result,round,site,timecontrol,white,whiteelo
0,captnswing,961,2004.11.27,ICS Rated Chess Match,1. e4 e5 2. Ne2 Nf6 3. d4 Nxe4 4. dxe5 Qh4 5. ...,0-1,?,?,120+10,TheMirage,741
1,alexcardoso,887,2004.11.27,ICS Rated Chess Match,1. e4 e5 2. Nf3 d6 3. Bc4 Nf6 4. Ng5 Be6 5. Bx...,*,?,?,120+12,captnswing,965
2,captnswing,965,2004.11.27,ICS Rated Chess Match,1. d4 d5 2. e3 c5 3. c3 e6 4. Bd3 Nf6 5. Nd2 B...,0-1,?,?,120+10,gjmata,1005
3,honkyboy,1032,2004.11.27,ICS Rated Chess Match,1. e4 e5 2. Nf3 Nc6 3. Bc4 h6 4. c3 Nf6 5. d3 ...,1-0,?,?,120+10,captnswing,974
4,alexcardoso,887,2004.11.27,ICS Rated Chess Match,1. e4 e5 2. Nf3 d6 3. Bc4 Nf6 4. Ng5 Be6 5. Bx...,*,?,?,120+12,captnswing,965
5,captnswing,983,2004.11.27,ICS Rated Chess Match,1. e4 e5 2. Nf3 d6 3. d3 Nf6 4. Nbd2 Be7 5. b3...,1-0,?,?,120+10,RainFall,934
6,alexcardoso,887,2004.11.27,ICS Rated Chess Match,1. e4 e5 2. Nf3 d6 3. Bc4 Nf6 4. Ng5 Be6 5. Bx...,1-0,?,?,120+12,captnswing,965
7,maucsc,990,2004.11.27,ICS Rated Chess Match,1. e4 e5 2. Nf3 d6 3. Bc4 a6 4. a4 h6 5. c3 Nf...,1-0,?,?,120+10,captnswing,980
8,captnswing,988,2004.11.27,ICS Rated Chess Match,1. g4 e5 2. Bg2 Nf6 3. c4 Nxg4 4. Nc3 Qh4 5. N...,0-1,?,?,120+10,sjames,1053
9,captnswing,997,2004.11.27,ICS Rated Chess Match,1. e4 e5 2. Nf3 d6 3. d4 Nf6 4. dxe5 Nxe4 5. e...,1/2-1/2,?,?,120+10,blerim,929
10,Edsmyr,981,2004.11.27,ICS Rated Chess Match,1. e4 e5 2. Nf3 Nf6 3. Bc4 Nxe4 4. Nxe5 d5 5. ...,1-0,?,?,300+12,captnswing,995
11,captnswing,1003,2004.11.27,ICS Rated Chess Match,1. e4 e5 2. Nf3 d6 3. d4 Nf6 4. dxe5 Nxe4 5. N...,0-1,?,?,300+12,Edsmyr,973
12,Edsmyr,966,2004.11.27,ICS Rated Chess Match,1. e4 e5 2. Nf3 Nf6 3. Bc4 Nxe4 4. Nxe5 d5 5. ...,0-1,?,?,300+12,captnswing,1010
13,captnswing,1001,2004.11.27,ICS Rated Chess Match,1. e4 e5 2. Nf3 d6 3. Bc4 Nf6 4. d3 Be7 5. Ng5...,1-0,?,?,120+10,Carita,1063

In [8]:
pd.DataFrame(process_pgnfile('freechess/fixtures/eboard.pgn'))

,date,opponent_elo,opponent_name,result,self_elo,self_white,timecontrol
0,2004-11-27,741,TheMirage,0-1,961,False,120+10
1,2004-11-27,1005,gjmata,0-1,965,False,120+10
2,2004-11-27,1032,honkyboy,1-0,974,True,120+10
3,2004-11-27,934,RainFall,1-0,983,False,120+10
4,2004-11-27,887,alexcardoso,1-0,965,True,120+12
5,2004-11-27,990,maucsc,1-0,980,True,120+10
6,2004-11-27,1053,sjames,0-1,988,False,120+10
7,2004-11-27,929,blerim,1/2-1/2,997,False,120+10
8,2004-11-27,981,Edsmyr,1-0,995,True,300+12
9,2004-11-27,973,Edsmyr,0-1,1003,False,300+12
10,2004-11-27,966,Edsmyr,0-1,1010,True,300+12
11,2004-11-27,1063,Carita,1-0,1001,False,120+10